spring:
  application:
    name: aicloud
  config:
    import: nacos:aicloud-config
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: openchat:7b
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
        context-path: /nacos
        namespace: public
        server-addr: localhost:8848
        group: DEFAULT_GROUP
        file-extension: yaml
server:
  port: 8080